// Schema for src/data/nb-objects.json, generated by scripts/scrape-liquid-objects.mjs
// from https://nationbuilder.com/liquid.

export interface NBProperty {
  /** Prose description of the property, as written in the NationBuilder docs. */
  description?: string;

  /** Example snippet from the docs, e.g. "e.g. {{ page.id }}". */
  example?: string;

  /** Dotted name of the NB object this property resolves to, if the docs link one. */
  type?: string;

  /** Set when the docs mark the property as no longer used. */
  deprecated?: true;
}

export interface NBObject {
  /** Doc page slug, e.g. "basic_page_variables". */
  slug: string;

  /** Display title from the doc page, e.g. "Basic page variables". */
  title: string;

  /** Intro text from the doc page, if any. */
  description?: string;
  
  properties: Record<string, NBProperty>;
}

/** Keyed by dotted object name, e.g. "page", "page.basic", "donation". */
export type NBObjectMap = Record<string, NBObject>;
